apiVersion: batch/v1
kind: Job
metadata:
  name: client
  labels:
    name: client
    app: client
spec:
  template:
    spec:
      containers:
      - name: dkrsmclient
        image: dkrsmclient
      restartPolicy: Never
  backoffLimit: 4

